- name: "type: bug"
  color: "d73a4a"
  description: "Something is not working"
- name: "type: feature"
  color: "0e8a16"
  description: "New feature or request"
- name: "type: maintenance"
  color: "1d76db"
  description: "Maintenance or chores"
- name: "priority: high"
  color: "b60205"
  description: "High priority"
- name: "priority: medium"
  color: "fbca04"
  description: "Medium priority"
- name: "priority: low"
  color: "c2e0c6"
  description: "Low priority"
