// Generated by env-typegen — do not edit manually
// Source: app.env.example
// Generated at: 2026-03-17T21:48:59.941Z

declare namespace NodeJS {
  interface ProcessEnv {
    readonly DATABASE_URL: string;
    readonly PORT: string; // coerce to number: Number(process.env.PORT)
    readonly NEXT_PUBLIC_APP_URL: string;
  }
}

export type EnvVars = {
  DATABASE_URL: string;
  PORT: number;
  NEXT_PUBLIC_APP_URL: string;
};

export type ServerEnvVars = Omit<EnvVars, "NEXT_PUBLIC_APP_URL">;
export type ClientEnvVars = Pick<EnvVars, "NEXT_PUBLIC_APP_URL">;
