// Generated by env-typegen — do not edit manually
// Source: app.env.example

declare namespace NodeJS {
  interface ProcessEnv {
    readonly DATABASE_URL: string;
    readonly PORT: string; // coerce to number: Number(process.env.PORT)
    readonly NEXT_PUBLIC_APP_URL: string;
  }
}
