// Generated by env-typegen — do not edit manually
// Source: basic.env.example
// Generated at: 2026-03-17T21:48:58.715Z

declare namespace NodeJS {
  interface ProcessEnv {
    /** Basic fixture */
    readonly DATABASE_URL: string;
    readonly PORT: string; // coerce to number: Number(process.env.PORT)
    readonly DEBUG: string; // coerce to boolean: process.env.DEBUG === 'true'
    readonly NODE_ENV: string;
    readonly AUTH_SECRET?: string;
    readonly WEBHOOK_URL: string;
  }
}

export type EnvVars = {
  DATABASE_URL: string;
  PORT: number;
  DEBUG: boolean;
  NODE_ENV: string;
  AUTH_SECRET?: string;
  WEBHOOK_URL: string;
};
