// Generated by env-typegen — do not edit manually
// Source: basic.env.example

declare namespace NodeJS {
  interface ProcessEnv {
    /** Basic fixture */
    readonly DATABASE_URL: string;
    readonly PORT: string; // coerce to number: Number(process.env.PORT)
    readonly DEBUG: string; // coerce to boolean: process.env.DEBUG === 'true'
    readonly NODE_ENV: string;
    readonly AUTH_SECRET?: string;
    readonly WEBHOOK_URL: string;
  }
}
