// Generated by env-typegen — do not edit manually
import { z } from "zod";

export const serverEnvSchema = z.object({
  DATABASE_URL: z.url(),
  PORT: z.coerce.number(),
});

export const clientEnvSchema = z.object({
  NEXT_PUBLIC_APP_URL: z.url(),
});

export const envSchema = z.object({
  ...serverEnvSchema.shape,
  ...clientEnvSchema.shape,
});
export type Env = z.infer<typeof envSchema>;
