// Generated by env-typegen — do not edit manually
import { z } from "zod";

export const serverEnvSchema = z.object({
  DATABASE_URL: z.url(),
  PORT: z.coerce.number(),
  DEBUG: z.coerce.boolean(),
  NODE_ENV: z.string(),
  AUTH_SECRET: z.string().optional(),
  WEBHOOK_URL: z.url(),
});

export const clientEnvSchema = z.object({});

export const envSchema = z.object({
  ...serverEnvSchema.shape,
  ...clientEnvSchema.shape,
});
export type Env = z.infer<typeof envSchema>;
