// Generated by env-typegen — do not edit manually
import { z } from "zod";

export const serverEnvSchema = z.object({
  API_URL: z.url(),
});

export const clientEnvSchema = z.object({});

export const envSchema = z.object({
  ...serverEnvSchema.shape,
  ...clientEnvSchema.shape,
});
export type Env = z.infer<typeof envSchema>;
