// Generated by env-typegen — do not edit manually
import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    DATABASE_URL: z.url().describe("Basic fixture"),
    PORT: z.coerce.number(),
    DEBUG: z.coerce.boolean(),
    NODE_ENV: z.string(),
    AUTH_SECRET: z.string().optional(),
    WEBHOOK_URL: z.url(),
  },
  runtimeEnv: {
    DATABASE_URL: process.env.DATABASE_URL,
    PORT: process.env.PORT,
    DEBUG: process.env.DEBUG,
    NODE_ENV: process.env.NODE_ENV,
    AUTH_SECRET: process.env.AUTH_SECRET,
    WEBHOOK_URL: process.env.WEBHOOK_URL,
  },
});
