// Generated by env-typegen — do not edit manually
import { z } from "zod";

export const serverEnvSchema = z.object({
  API_URL: z.url(),
  SMTP_FROM: z.email(),
  SUPPORT_EMAIL: z.email(),
  ENABLE_ANALYTICS: z.coerce.boolean(),
  DISABLE_CACHE: z.coerce.boolean(),
  IS_PRODUCTION: z.coerce.boolean(),
  DEBUG: z.coerce.boolean(),
  FEATURE_NEW_UI: z.coerce.boolean(),
  DATABASE_PORT: z.coerce.number(),
  PORT: z.coerce.number(),
  MISSING_VAR: z.string().optional(),
  SOME_TOGGLE: z.coerce.boolean(),
  TIMEOUT_MS: z.coerce.number(),
  RATIO: z.coerce.number(),
  APP_VERSION: z.string(),
  WEBHOOK: z.url(),
});

export const clientEnvSchema = z.object({});

export const envSchema = z.object({
  ...serverEnvSchema.shape,
  ...clientEnvSchema.shape,
});
export type Env = z.infer<typeof envSchema>;
