// Generated by env-typegen — do not edit manually
// Source: types.env.example
// Generated at: 2026-03-17T22:12:01.265Z

declare namespace NodeJS {
  interface ProcessEnv {
    readonly API_URL: string;
    readonly SMTP_FROM: string;
    readonly SUPPORT_EMAIL: string;
    readonly ENABLE_ANALYTICS: string; // coerce to boolean: process.env.ENABLE_ANALYTICS === 'true'
    readonly DISABLE_CACHE: string; // coerce to boolean: process.env.DISABLE_CACHE === 'true'
    readonly IS_PRODUCTION: string; // coerce to boolean: process.env.IS_PRODUCTION === 'true'
    readonly DEBUG: string; // coerce to boolean: process.env.DEBUG === 'true'
    readonly FEATURE_NEW_UI: string; // coerce to boolean: process.env.FEATURE_NEW_UI === 'true'
    readonly DATABASE_PORT: string; // coerce to number: Number(process.env.DATABASE_PORT)
    readonly PORT: string;
    readonly MISSING_VAR?: string;
    readonly SOME_TOGGLE: string; // coerce to boolean: process.env.SOME_TOGGLE === 'true'
    readonly TIMEOUT_MS: string; // coerce to number: Number(process.env.TIMEOUT_MS)
    readonly RATIO: string; // coerce to number: Number(process.env.RATIO)
    readonly APP_VERSION: string;
    readonly WEBHOOK: string;
  }
}

export type EnvVars = {
  API_URL: string;
  SMTP_FROM: string;
  SUPPORT_EMAIL: string;
  ENABLE_ANALYTICS: boolean;
  DISABLE_CACHE: boolean;
  IS_PRODUCTION: boolean;
  DEBUG: boolean;
  FEATURE_NEW_UI: boolean;
  DATABASE_PORT: number;
  PORT: string;
  MISSING_VAR?: string;
  SOME_TOGGLE: boolean;
  TIMEOUT_MS: number;
  RATIO: number;
  APP_VERSION: string;
  WEBHOOK: string;
};
