import path from "node:path";

import type { ParsedEnvFile } from "../parser/types.js";

/**
 * Generates an ambient `.d.ts` declaration file from a parsed .env.example.
 *
 * Output is a pure `NodeJS.ProcessEnv` augmentation — no `export type` statements.
 * This makes the file valid as a global ambient declaration that can be dropped
 * into `lib/` or `types/` without affecting module resolution.
 *
 * Output structure:
 * ```
 * // Generated by env-typegen — do not edit manually
 * // Source: .env.example
 *
 * declare namespace NodeJS {
 *   interface ProcessEnv {
 *     readonly KEY: string;     // all vars are runtime strings
 *     readonly OPT?: string;    // optional vars use ?: string
 *     readonly NUM: string;     // coerce to number: Number(process.env.NUM)
 *     readonly FLAG: string;    // coerce to boolean: process.env.FLAG === 'true'
 *   }
 * }
 * ```
 *
 * For a `.ts` output with typed `export type EnvVars` / `ServerEnvVars` /
 * `ClientEnvVars`, use `generateTypeScriptTypes` instead.
 *
 * - `ProcessEnv` uses `readonly string` for every variable (runtime reality)
 * - Number and boolean vars include an inline coercion hint comment
 * - `annotatedType` takes precedence over `inferredType`
 */
export function generateDeclaration(parsed: ParsedEnvFile): string {
  const fileName = path.basename(parsed.filePath);
  const lines: string[] = [];

  // Header
  lines.push("// Generated by env-typegen — do not edit manually");
  lines.push(`// Source: ${fileName}`);
  lines.push("");

  // NodeJS.ProcessEnv augmentation — ambient only, no exports
  lines.push("declare namespace NodeJS {");
  lines.push("  interface ProcessEnv {");
  for (const variable of parsed.vars) {
    const effectiveType = variable.annotatedType ?? variable.inferredType;
    const optional = variable.isOptional ? "?" : "";
    if (variable.description !== undefined) {
      lines.push(`    /** ${variable.description} */`);
    }
    let propLine = `    readonly ${variable.key}${optional}: string;`;
    if (effectiveType === "number") {
      propLine += ` // coerce to number: Number(process.env.${variable.key})`;
    } else if (effectiveType === "boolean") {
      propLine += ` // coerce to boolean: process.env.${variable.key} === 'true'`;
    }
    lines.push(propLine);
  }
  lines.push("  }");
  lines.push("}");

  return lines.join("\n") + "\n";
}
