import type { EnvVarType, ParsedEnvFile } from "../parser/types.js";

/**
 * Escapes a string for safe embedding inside a double-quoted JavaScript string
 * literal. Backslashes must be escaped before double quotes so that a backslash
 * at the end of the value does not inadvertently escape the closing quote.
 */
function escapeJsStringLiteral(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

/**
 * Maps an EnvVarType to its Zod schema expression for use in t3-env createEnv().
 *
 * Note: boolean uses `z.coerce.boolean()` here (not the `.transform()` approach
 * in the standalone zod-generator) because @t3-oss/env-nextjs handles coercion
 * internally with `z.coerce`.
 */
function toT3ZodType(envVarType: EnvVarType): string {
  if (envVarType === "number") return "z.coerce.number()";
  if (envVarType === "boolean") return "z.coerce.boolean()";
  if (envVarType === "url") return "z.string().url()";
  if (envVarType === "email") return "z.string().email()";
  return "z.string()";
}

/**
 * Generates a `@t3-oss/env-nextjs` configuration file from a parsed .env.example.
 *
 * Output structure:
 * ```
 * import { createEnv } from "@t3-oss/env-nextjs";
 * import { z } from "zod";
 *
 * export const env = createEnv({
 *   server: { /* non-NEXT_PUBLIC_ vars *\/ },
 *   client: { /* NEXT_PUBLIC_ vars *\/ },
 *   runtimeEnv: { /* all vars mapped to process.env *\/ },
 * });
 * ```
 *
 * - `server:` is omitted when there are no server-side vars
 * - `client:` is omitted when there are no client-side vars (NEXT_PUBLIC_ prefix)
 * - `runtimeEnv:` always includes all vars
 * - `annotatedType` takes precedence over `inferredType`
 * - Optional vars have `.optional()` appended
 * - Vars with a description have `.describe("text")` appended (before `.optional()`)
 */
export function generateT3Env(parsed: ParsedEnvFile): string {
  const serverVars = parsed.vars.filter((v) => !v.isClientSide);
  const clientVars = parsed.vars.filter((v) => v.isClientSide);
  const lines: string[] = [];

  lines.push("// Generated by env-typegen — do not edit manually");
  lines.push('import { createEnv } from "@t3-oss/env-nextjs";');
  lines.push('import { z } from "zod";');
  lines.push("");
  lines.push("export const env = createEnv({");

  if (serverVars.length > 0) {
    lines.push("  server: {");
    for (const variable of serverVars) {
      const effectiveType = variable.annotatedType ?? variable.inferredType;
      let zodExpr = toT3ZodType(effectiveType);
      if (variable.description !== undefined) {
        zodExpr += `.describe("${escapeJsStringLiteral(variable.description)}")`;
      }
      if (variable.isOptional) {
        zodExpr += ".optional()";
      }
      lines.push(`    ${variable.key}: ${zodExpr},`);
    }
    lines.push("  },");
  }

  if (clientVars.length > 0) {
    lines.push("  client: {");
    for (const variable of clientVars) {
      const effectiveType = variable.annotatedType ?? variable.inferredType;
      let zodExpr = toT3ZodType(effectiveType);
      if (variable.description !== undefined) {
        zodExpr += `.describe("${escapeJsStringLiteral(variable.description)}")`;
      }
      if (variable.isOptional) {
        zodExpr += ".optional()";
      }
      lines.push(`    ${variable.key}: ${zodExpr},`);
    }
    lines.push("  },");
  }

  lines.push("  runtimeEnv: {");
  for (const variable of parsed.vars) {
    lines.push(`    ${variable.key}: process.env.${variable.key},`);
  }
  lines.push("  },");
  lines.push("});");

  return lines.join("\n") + "\n";
}
