import path from "node:path";

import type { EnvVarType, ParsedEnvFile } from "../parser/types.js";

/**
 * Maps an EnvVarType to its TypeScript primitive equivalent.
 * url, email, semver, json, and unknown all map to `string` because
 * TypeScript has no built-in branded types for these.
 */
function toTsType(envVarType: EnvVarType): string {
  if (envVarType === "number") return "number";
  if (envVarType === "boolean") return "boolean";
  return "string";
}

/**
 * Generates a TypeScript source file from a parsed .env.example file.
 *
 * Output structure:
 * 1. Header comments — generated-by notice, source file name, ISO timestamp
 * 2. `declare namespace NodeJS { interface ProcessEnv { ... } }` — global augmentation
 *    where all properties are typed as `readonly string` (the runtime reality).
 *    Number and boolean vars include an inline coercion hint comment.
 * 3. `export type EnvVars = { ... }` — typed module export using semantic types
 *    (number, boolean, string).
 * 4. `ServerEnvVars` / `ClientEnvVars` — emitted only when `NEXT_PUBLIC_` vars exist.
 *
 * The output is valid as both a `.ts` and `.d.ts` file.
 * For an ambient-only `.d.ts` (without `export type` statements), use
 * `generateDeclaration` instead.
 *
 * `annotatedType` takes precedence over `inferredType` when both are set.
 */
export function generateTypeScriptTypes(parsed: ParsedEnvFile): string {
  const clientVars = parsed.vars.filter((v) => v.isClientSide);
  const hasClientVars = clientVars.length > 0;
  const fileName = path.basename(parsed.filePath);
  const timestamp = new Date().toISOString();
  const lines: string[] = [];

  // Header
  lines.push("// Generated by env-typegen — do not edit manually");
  lines.push(`// Source: ${fileName}`);
  lines.push(`// Generated at: ${timestamp}`);
  lines.push("");

  // NodeJS.ProcessEnv augmentation — all props are runtime strings with optional coercion hints
  lines.push("declare namespace NodeJS {");
  lines.push("  interface ProcessEnv {");
  for (const variable of parsed.vars) {
    const effectiveType = variable.annotatedType ?? variable.inferredType;
    const optional = variable.isOptional ? "?" : "";
    if (variable.description !== undefined) {
      lines.push(`    /** ${variable.description} */`);
    }
    let propLine = `    readonly ${variable.key}${optional}: string;`;
    if (effectiveType === "number") {
      propLine += ` // coerce to number: Number(process.env.${variable.key})`;
    } else if (effectiveType === "boolean") {
      propLine += ` // coerce to boolean: process.env.${variable.key} === 'true'`;
    }
    lines.push(propLine);
  }
  lines.push("  }");
  lines.push("}");
  lines.push("");

  // EnvVars type with semantic TypeScript types
  lines.push("export type EnvVars = {");
  for (const variable of parsed.vars) {
    const effectiveType = variable.annotatedType ?? variable.inferredType;
    const tsType = toTsType(effectiveType);
    const optional = variable.isOptional ? "?" : "";
    lines.push(`  ${variable.key}${optional}: ${tsType};`);
  }
  lines.push("};");

  // ServerEnvVars / ClientEnvVars — only emitted when NEXT_PUBLIC_ vars exist
  if (hasClientVars) {
    const clientKeyUnion = clientVars.map((v) => `"${v.key}"`).join(" | ");
    lines.push("");
    lines.push(`export type ServerEnvVars = Omit<EnvVars, ${clientKeyUnion}>;`);
    lines.push(`export type ClientEnvVars = Pick<EnvVars, ${clientKeyUnion}>;`);
  }

  return lines.join("\n") + "\n";
}

/**
 * Generates a runtime `validateEnv()` function that throws when any required
 * environment variable is absent from `process.env`.
 */
export function generateEnvValidation(parsed: ParsedEnvFile): string {
  const required = parsed.vars.filter((v) => v.isRequired).map((v) => v.key);
  const lines: string[] = [];

  lines.push("// Generated by env-typegen — do not edit manually");
  lines.push("");
  lines.push("export function validateEnv(): void {");

  if (required.length === 0) {
    lines.push("  // No required environment variables defined");
  } else {
    const keyList = required.map((k) => `"${k}"`).join(", ");
    lines.push(`  const required = [${keyList}];`);
    lines.push("  for (const key of required) {");
    lines.push("    if (!process.env[key]) {");
    lines.push("      throw new Error(`Missing required environment variable: ${key}`);");
    lines.push("    }");
    lines.push("  }");
  }

  lines.push("}");

  return lines.join("\n") + "\n";
}
