import type { EnvVarType, ParsedEnvFile } from "../parser/types.js";

/**
 * Maps an EnvVarType to its Zod schema expression.
 *
 * - `number`  → `z.coerce.number()` (env vars are strings; coerce handles the cast)
 * - `boolean` → `z.coerce.boolean()` (env vars are strings; coerce handles truthy cast)
 * - `url`     → `z.string().url()`
 * - `email`   → `z.string().email()`
 * - everything else → `z.string()` (string | semver | json | unknown)
 */
function toZodType(envVarType: EnvVarType): string {
  if (envVarType === "number") return "z.coerce.number()";
  if (envVarType === "boolean") return "z.coerce.boolean()";
  if (envVarType === "url") return "z.string().url()";
  if (envVarType === "email") return "z.string().email()";
  return "z.string()";
}

/**
 * Generates a Zod schema file from a parsed .env.example file.
 *
 * Output structure:
 * ```
 * // Generated by env-typegen — do not edit manually
 * import { z } from "zod";
 *
 * export const serverEnvSchema = z.object({
 *   DATABASE_URL: z.string().url(),
 *   PORT: z.coerce.number(),
 * });
 *
 * export const clientEnvSchema = z.object({
 *   NEXT_PUBLIC_API_URL: z.string().url(),
 * });
 *
 * export const envSchema = serverEnvSchema.merge(clientEnvSchema);
 * export type Env = z.infer<typeof envSchema>;
 * ```
 *
 * - Server-side vars (non-`NEXT_PUBLIC_`) go into `serverEnvSchema`
 * - Client-side vars (`NEXT_PUBLIC_` prefix) go into `clientEnvSchema`
 * - `envSchema` is the merged union of both, for full-stack validation
 * - `annotatedType` takes precedence over `inferredType` when both are set
 * - Optional vars have `.optional()` appended to their Zod expression
 */
export function generateZodSchema(parsed: ParsedEnvFile): string {
  const serverVars = parsed.vars.filter((v) => !v.isClientSide);
  const clientVars = parsed.vars.filter((v) => v.isClientSide);
  const lines: string[] = [];

  // Header + open serverEnvSchema
  lines.push(
    "// Generated by env-typegen — do not edit manually",
    'import { z } from "zod";',
    "",
    "export const serverEnvSchema = z.object({",
  );
  for (const variable of serverVars) {
    const effectiveType = variable.annotatedType ?? variable.inferredType;
    const zodExpr = variable.isOptional
      ? `${toZodType(effectiveType)}.optional()`
      : toZodType(effectiveType);
    lines.push(`  ${variable.key}: ${zodExpr},`);
  }
  // Close serverEnvSchema + open clientEnvSchema
  lines.push("});", "", "export const clientEnvSchema = z.object({");
  for (const variable of clientVars) {
    const effectiveType = variable.annotatedType ?? variable.inferredType;
    const zodExpr = variable.isOptional
      ? `${toZodType(effectiveType)}.optional()`
      : toZodType(effectiveType);
    lines.push(`  ${variable.key}: ${zodExpr},`);
  }
  // Close clientEnvSchema + merged schema + type
  lines.push(
    "});",
    "",
    "export const envSchema = serverEnvSchema.merge(clientEnvSchema);",
    "export type Env = z.infer<typeof envSchema>;",
  );

  return lines.join("\n") + "\n";
}
