// Generated by env-typegen — do not edit manually
// Source: .env.staging
// Generated at: 2026-03-17T18:53:26.390Z

declare namespace NodeJS {
  interface ProcessEnv {
    readonly NODE_ENV: string;
    readonly PORT: string; // coerce to number: Number(process.env.PORT)
    readonly APP_URL: string;
    readonly DATABASE_URL: string;
    readonly AUTH_SECRET: string;
    readonly JWT_EXPIRY_SECONDS: string; // coerce to number: Number(process.env.JWT_EXPIRY_SECONDS)
    readonly ENABLE_BETA_FEATURES: string; // coerce to boolean: process.env.ENABLE_BETA_FEATURES === 'true'
    readonly MAX_UPLOAD_SIZE: string; // coerce to number: Number(process.env.MAX_UPLOAD_SIZE)
    readonly ALLOWED_ORIGINS: string;
    readonly SENTRY_DSN: string;
  }
}

export type EnvVars = {
  NODE_ENV: string;
  PORT: number;
  APP_URL: string;
  DATABASE_URL: string;
  AUTH_SECRET: string;
  JWT_EXPIRY_SECONDS: number;
  ENABLE_BETA_FEATURES: boolean;
  MAX_UPLOAD_SIZE: number;
  ALLOWED_ORIGINS: string;
  SENTRY_DSN: string;
};
