// Generated by env-typegen — do not edit manually
import { z } from "zod";

export const serverEnvSchema = z.object({
  NODE_ENV: z.string(),
  PORT: z.coerce.number(),
  APP_URL: z.string().url(),
  DATABASE_URL: z.string().url(),
  DATABASE_READONLY_URL: z.string().url(),
  AUTH_SECRET: z.string(),
  JWT_EXPIRY_SECONDS: z.coerce.number(),
  ENABLE_BETA_FEATURES: z.coerce.boolean(),
  MAX_UPLOAD_SIZE: z.coerce.number(),
  ALLOWED_ORIGINS: z.string(),
});

export const clientEnvSchema = z.object({});

export const envSchema = serverEnvSchema.merge(clientEnvSchema);
export type Env = z.infer<typeof envSchema>;
