// Generated by env-typegen — do not edit manually
import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    NODE_ENV: z.string().describe("Core"),
    PORT: z.coerce.number(),
    APP_URL: z.string().url(),
    DATABASE_URL: z.string().url().describe("DB"),
    DATABASE_READONLY_URL: z.string().url(),
    AUTH_SECRET: z.string().describe("Auth"),
    JWT_EXPIRY_SECONDS: z.coerce.number(),
    ENABLE_BETA_FEATURES: z.coerce.boolean().describe("Flags"),
    MAX_UPLOAD_SIZE: z.coerce.number(),
    ALLOWED_ORIGINS: z.string(),
  },
  runtimeEnv: {
    NODE_ENV: process.env.NODE_ENV,
    PORT: process.env.PORT,
    APP_URL: process.env.APP_URL,
    DATABASE_URL: process.env.DATABASE_URL,
    DATABASE_READONLY_URL: process.env.DATABASE_READONLY_URL,
    AUTH_SECRET: process.env.AUTH_SECRET,
    JWT_EXPIRY_SECONDS: process.env.JWT_EXPIRY_SECONDS,
    ENABLE_BETA_FEATURES: process.env.ENABLE_BETA_FEATURES,
    MAX_UPLOAD_SIZE: process.env.MAX_UPLOAD_SIZE,
    ALLOWED_ORIGINS: process.env.ALLOWED_ORIGINS,
  },
});
