// Generated by env-typegen — do not edit manually
// Source: app.env.example
// Generated at: 2026-03-17T20:46:59.642Z

declare namespace NodeJS {
  interface ProcessEnv {
    /** Non-dotfile input para prueba multi-input sin colisión de stem */
    readonly APP_SECRET: string;
    readonly APP_PORT: string; // coerce to number: Number(process.env.APP_PORT)
    readonly APP_DEBUG: string; // coerce to boolean: process.env.APP_DEBUG === 'true'
  }
}

export type EnvVars = {
  APP_SECRET: string;
  APP_PORT: number;
  APP_DEBUG: boolean;
};
