// Generated by env-typegen — do not edit manually
// Source: .env.extra
// Generated at: 2026-03-17T20:47:24.691Z

declare namespace NodeJS {
  interface ProcessEnv {
    /** Segundo dotfile de input para probar multi-input con dotfiles y colisión de stem */
    readonly REDIS_URL: string;
    readonly REDIS_MAX_POOL: string; // coerce to number: Number(process.env.REDIS_MAX_POOL)
    readonly CACHE_TTL: string; // coerce to number: Number(process.env.CACHE_TTL)
  }
}

export type EnvVars = {
  REDIS_URL: string;
  REDIS_MAX_POOL: number;
  CACHE_TTL: number;
};
