// Generated by env-typegen — do not edit manually
// Source: .env.example
// Generated at: 2026-03-17T20:45:21.215Z

declare namespace NodeJS {
  interface ProcessEnv {
    /** Main PostgreSQL connection string */
    readonly DATABASE_URL: string;
    /** Read replica URL (optional) */
    readonly DATABASE_READONLY_URL?: string;
    readonly PORT: string; // coerce to number: Number(process.env.PORT)
    readonly MAX_CONNECTIONS: string; // coerce to number: Number(process.env.MAX_CONNECTIONS)
    readonly DEBUG: string; // coerce to boolean: process.env.DEBUG === 'true'
    readonly NODE_ENV: string;
    /** Application secret — must be at least 32 chars */
    readonly AUTH_SECRET: string;
    /** JWT secret (alias) */
    readonly JWT_SECRET?: string;
    readonly API_BASE_URL: string;
    readonly WEBHOOK_URL: string;
    readonly SMTP_FROM: string;
    readonly SMTP_HOST: string;
    readonly SMTP_PORT: string; // coerce to number: Number(process.env.SMTP_PORT)
    readonly ENABLE_ANALYTICS: string; // coerce to boolean: process.env.ENABLE_ANALYTICS === 'true'
    readonly ENABLE_MAINTENANCE_MODE: string; // coerce to boolean: process.env.ENABLE_MAINTENANCE_MODE === 'true'
    readonly APP_VERSION: string;
    readonly APP_NAME: string;
    readonly NEXT_PUBLIC_APP_URL: string;
    readonly NEXT_PUBLIC_FEATURE_FLAGS: string;
  }
}

export type EnvVars = {
  DATABASE_URL: string;
  DATABASE_READONLY_URL?: string;
  PORT: number;
  MAX_CONNECTIONS: number;
  DEBUG: boolean;
  NODE_ENV: string;
  AUTH_SECRET: string;
  JWT_SECRET?: string;
  API_BASE_URL: string;
  WEBHOOK_URL: string;
  SMTP_FROM: string;
  SMTP_HOST: string;
  SMTP_PORT: number;
  ENABLE_ANALYTICS: boolean;
  ENABLE_MAINTENANCE_MODE: boolean;
  APP_VERSION: string;
  APP_NAME: string;
  NEXT_PUBLIC_APP_URL: string;
  NEXT_PUBLIC_FEATURE_FLAGS: string;
};

export type ServerEnvVars = Omit<
  EnvVars,
  "NEXT_PUBLIC_APP_URL" | "NEXT_PUBLIC_FEATURE_FLAGS"
>;
export type ClientEnvVars = Pick<
  EnvVars,
  "NEXT_PUBLIC_APP_URL" | "NEXT_PUBLIC_FEATURE_FLAGS"
>;
