// Generated by env-typegen — do not edit manually
import { z } from "zod";

export const serverEnvSchema = z.object({
  DATABASE_URL: z.string().url(),
  DATABASE_READONLY_URL: z.string().url().optional(),
  PORT: z.coerce.number(),
  MAX_CONNECTIONS: z.coerce.number(),
  DEBUG: z.coerce.boolean(),
  NODE_ENV: z.string(),
  AUTH_SECRET: z.string(),
  JWT_SECRET: z.string().optional(),
  API_BASE_URL: z.string().url(),
  WEBHOOK_URL: z.string().url(),
  SMTP_FROM: z.string().email(),
  SMTP_HOST: z.string(),
  SMTP_PORT: z.coerce.number(),
  ENABLE_ANALYTICS: z.coerce.boolean(),
  ENABLE_MAINTENANCE_MODE: z.coerce.boolean(),
  APP_VERSION: z.string(),
  APP_NAME: z.string(),
});

export const clientEnvSchema = z.object({
  NEXT_PUBLIC_APP_URL: z.string().url(),
  NEXT_PUBLIC_FEATURE_FLAGS: z.string(),
});

export const envSchema = serverEnvSchema.merge(clientEnvSchema);
export type Env = z.infer<typeof envSchema>;
