// Generated by env-typegen — do not edit manually
import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    DATABASE_URL: z.url().describe("Main PostgreSQL connection string"),
    DATABASE_READONLY_URL: z
      .url()
      .describe("Read replica URL (optional)")
      .optional(),
    PORT: z.coerce.number(),
    MAX_CONNECTIONS: z.coerce.number(),
    DEBUG: z.coerce.boolean(),
    NODE_ENV: z.string(),
    AUTH_SECRET: z
      .string()
      .describe("Application secret — must be at least 32 chars"),
    JWT_SECRET: z.string().describe("JWT secret (alias)").optional(),
    API_BASE_URL: z.url(),
    WEBHOOK_URL: z.url(),
    SMTP_FROM: z.email(),
    SMTP_HOST: z.string(),
    SMTP_PORT: z.coerce.number(),
    ENABLE_ANALYTICS: z.coerce.boolean(),
    ENABLE_MAINTENANCE_MODE: z.coerce.boolean(),
    APP_VERSION: z.string(),
    APP_NAME: z.string(),
  },
  client: {
    NEXT_PUBLIC_APP_URL: z.url(),
    NEXT_PUBLIC_FEATURE_FLAGS: z.string(),
  },
  runtimeEnv: {
    DATABASE_URL: process.env.DATABASE_URL,
    DATABASE_READONLY_URL: process.env.DATABASE_READONLY_URL,
    PORT: process.env.PORT,
    MAX_CONNECTIONS: process.env.MAX_CONNECTIONS,
    DEBUG: process.env.DEBUG,
    NODE_ENV: process.env.NODE_ENV,
    AUTH_SECRET: process.env.AUTH_SECRET,
    JWT_SECRET: process.env.JWT_SECRET,
    API_BASE_URL: process.env.API_BASE_URL,
    WEBHOOK_URL: process.env.WEBHOOK_URL,
    SMTP_FROM: process.env.SMTP_FROM,
    SMTP_HOST: process.env.SMTP_HOST,
    SMTP_PORT: process.env.SMTP_PORT,
    ENABLE_ANALYTICS: process.env.ENABLE_ANALYTICS,
    ENABLE_MAINTENANCE_MODE: process.env.ENABLE_MAINTENANCE_MODE,
    APP_VERSION: process.env.APP_VERSION,
    APP_NAME: process.env.APP_NAME,
    NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
    NEXT_PUBLIC_FEATURE_FLAGS: process.env.NEXT_PUBLIC_FEATURE_FLAGS,
  },
});
