// Generated by env-typegen — do not edit manually
// Source: .env.example

declare namespace NodeJS {
  interface ProcessEnv {
    /** Main PostgreSQL connection string */
    readonly DATABASE_URL: string;
    /** Read replica URL (optional) */
    readonly DATABASE_READONLY_URL?: string;
    readonly PORT: string; // coerce to number: Number(process.env.PORT)
    readonly MAX_CONNECTIONS: string; // coerce to number: Number(process.env.MAX_CONNECTIONS)
    readonly DEBUG: string; // coerce to boolean: process.env.DEBUG === 'true'
    readonly NODE_ENV: string;
    /** Application secret — must be at least 32 chars */
    readonly AUTH_SECRET: string;
    /** JWT secret (alias) */
    readonly JWT_SECRET?: string;
    readonly API_BASE_URL: string;
    readonly WEBHOOK_URL: string;
    readonly SMTP_FROM: string;
    readonly SMTP_HOST: string;
    readonly SMTP_PORT: string; // coerce to number: Number(process.env.SMTP_PORT)
    readonly ENABLE_ANALYTICS: string; // coerce to boolean: process.env.ENABLE_ANALYTICS === 'true'
    readonly ENABLE_MAINTENANCE_MODE: string; // coerce to boolean: process.env.ENABLE_MAINTENANCE_MODE === 'true'
    readonly APP_VERSION: string;
    readonly APP_NAME: string;
    readonly NEXT_PUBLIC_APP_URL: string;
    readonly NEXT_PUBLIC_FEATURE_FLAGS: string;
  }
}
