// Generated by env-typegen — do not edit manually
// Source: local.env.example
// Generated at: 2026-03-17T20:46:59.645Z

declare namespace NodeJS {
  interface ProcessEnv {
    /** Segundo non-dotfile para multi-input */
    readonly QUEUE_URL: string;
    readonly QUEUE_WORKERS: string; // coerce to number: Number(process.env.QUEUE_WORKERS)
    readonly QUEUE_RETRY: string; // coerce to number: Number(process.env.QUEUE_RETRY)
  }
}

export type EnvVars = {
  QUEUE_URL: string;
  QUEUE_WORKERS: number;
  QUEUE_RETRY: number;
};
