import { describe, expect, it } from "vitest";
import { generateDeclaration } from "../../src/generators/declaration-generator.js";
import { parseEnvFileContent } from "../../src/parser/env-parser.js";

describe("generateDeclaration", () => {
  describe("header comments", () => {
    it("should include the generated-by header comment", () => {
      const parsed = parseEnvFileContent("KEY=value", ".env.example");
      const output = generateDeclaration(parsed);
      expect(output).toContain("// Generated by env-typegen");
    });

    it("should include the source filename in a comment", () => {
      const parsed = parseEnvFileContent("KEY=value", "/project/.env.example");
      const output = generateDeclaration(parsed);
      expect(output).toContain("// Source: .env.example");
    });

    it("should use only the basename for the source filename", () => {
      const parsed = parseEnvFileContent("KEY=value", "/some/deep/path/my.env.local");
      const output = generateDeclaration(parsed);
      expect(output).toContain("// Source: my.env.local");
      expect(output).not.toContain("/some/deep/path/");
    });
  });

  describe("NodeJS.ProcessEnv augmentation", () => {
    it("should declare the NodeJS namespace", () => {
      const parsed = parseEnvFileContent("KEY=value", ".env.example");
      const output = generateDeclaration(parsed);
      expect(output).toContain("declare namespace NodeJS {");
    });

    it("should augment the ProcessEnv interface", () => {
      const parsed = parseEnvFileContent("KEY=value", ".env.example");
      const output = generateDeclaration(parsed);
      expect(output).toContain("interface ProcessEnv {");
    });

    it("should emit required vars as readonly string", () => {
      const parsed = parseEnvFileContent("API_KEY=sk-abc123", ".env.example");
      const output = generateDeclaration(parsed);
      expect(output).toContain("readonly API_KEY: string;");
    });

    it("should emit optional vars as readonly ?: string", () => {
      const parsed = parseEnvFileContent("WEBHOOK_URL=", ".env.example");
      const output = generateDeclaration(parsed);
      expect(output).toContain("readonly WEBHOOK_URL?: string;");
    });

    it("should add a JSDoc comment when description is set", () => {
      const content = "# @description Main database URL\nDATABASE_URL=postgres://localhost/db";
      const parsed = parseEnvFileContent(content, ".env.example");
      const output = generateDeclaration(parsed);
      expect(output).toContain("/** Main database URL */");
    });

    it("should add an inline coercion hint for number vars", () => {
      const parsed = parseEnvFileContent("PORT=3000", ".env.example");
      const output = generateDeclaration(parsed);
      expect(output).toContain("// coerce to number: Number(process.env.PORT)");
    });

    it("should add an inline coercion hint for boolean vars", () => {
      const parsed = parseEnvFileContent("DEBUG=true", ".env.example");
      const output = generateDeclaration(parsed);
      expect(output).toContain("// coerce to boolean: process.env.DEBUG === 'true'");
    });

    it("should not add a coercion hint for plain string vars", () => {
      const parsed = parseEnvFileContent("TOKEN=abc", ".env.example");
      const output = generateDeclaration(parsed);
      const line = output.split("\n").find((l) => l.includes("TOKEN:")) ?? "";
      expect(line).not.toContain("// coerce");
    });

    it("should still type all ProcessEnv properties as string (even numbers/booleans)", () => {
      const content = "PORT=3000\nDEBUG=true\nNAME=myapp";
      const parsed = parseEnvFileContent(content, ".env.example");
      const output = generateDeclaration(parsed);
      // All ProcessEnv properties are runtime strings
      expect(output).toContain("readonly PORT: string;");
      expect(output).toContain("readonly DEBUG: string;");
      expect(output).toContain("readonly NAME: string;");
    });
  });

  describe("annotatedType override", () => {
    it("should use annotatedType over inferredType in ProcessEnv coercion hint", () => {
      // PORT=3000 would infer 'number' → coercion hint; @type boolean overrides to boolean hint
      const content = "# @type boolean\nPORT=3000";
      const parsed = parseEnvFileContent(content, ".env.example");
      const output = generateDeclaration(parsed);
      expect(output).toContain("// coerce to boolean:");
      expect(output).not.toContain("// coerce to number:");
    });
  });
});
