import { describe, expect, it } from "vitest";
import {
  generateEnvValidation,
  generateTypeScriptTypes,
} from "../../src/generators/typescript-generator.js";
import { parseEnvFileContent } from "../../src/parser/env-parser.js";

describe("generateTypeScriptTypes", () => {
  describe("header comments", () => {
    it("should include the generated-by notice", () => {
      const parsed = parseEnvFileContent("KEY=value", "/test.env");
      const output = generateTypeScriptTypes(parsed);
      expect(output).toContain("// Generated by env-typegen — do not edit manually");
    });

    it("should include the source file name", () => {
      const parsed = parseEnvFileContent("KEY=value", "/path/to/test.env");
      const output = generateTypeScriptTypes(parsed);
      expect(output).toContain("// Source: test.env");
    });

    it("should include a Generated at ISO timestamp", () => {
      const parsed = parseEnvFileContent("KEY=value", "/test.env");
      const output = generateTypeScriptTypes(parsed);
      expect(output).toMatch(/\/\/ Generated at: \d{4}-\d{2}-\d{2}T/);
    });
  });

  describe("NodeJS.ProcessEnv augmentation", () => {
    it("should emit the NodeJS namespace and ProcessEnv interface", () => {
      const parsed = parseEnvFileContent("KEY=value", "/test.env");
      const output = generateTypeScriptTypes(parsed);
      expect(output).toContain("declare namespace NodeJS {");
      expect(output).toContain("  interface ProcessEnv {");
    });

    it("should type all vars as readonly string in ProcessEnv", () => {
      const parsed = parseEnvFileContent("DATABASE_URL=postgresql://localhost/db", "/test.env");
      const output = generateTypeScriptTypes(parsed);
      expect(output).toContain("readonly DATABASE_URL: string;");
    });

    it("should mark optional vars with ?: string in ProcessEnv", () => {
      const parsed = parseEnvFileContent("AUTH_SECRET=", "/test.env");
      const output = generateTypeScriptTypes(parsed);
      expect(output).toContain("readonly AUTH_SECRET?: string;");
    });

    it("should add a coercion hint comment for number vars in ProcessEnv", () => {
      const parsed = parseEnvFileContent("PORT=3000", "/test.env");
      const output = generateTypeScriptTypes(parsed);
      expect(output).toContain(
        "readonly PORT: string; // coerce to number: Number(process.env.PORT)",
      );
    });

    it("should add a coercion hint comment for boolean vars in ProcessEnv", () => {
      const parsed = parseEnvFileContent("DEBUG=true", "/test.env");
      const output = generateTypeScriptTypes(parsed);
      expect(output).toContain(
        "readonly DEBUG: string; // coerce to boolean: process.env.DEBUG === 'true'",
      );
    });

    it("should not add a coercion hint for plain string vars", () => {
      const parsed = parseEnvFileContent("NODE_ENV=development", "/test.env");
      const output = generateTypeScriptTypes(parsed);
      expect(output).toContain("readonly NODE_ENV: string;");
      expect(output).not.toContain("// coerce");
    });

    it("should include a JSDoc comment for vars with a description", () => {
      const content = [
        "# @description Main database connection URL",
        "DATABASE_URL=postgresql://localhost/db",
      ].join("\n");
      const parsed = parseEnvFileContent(content, "/test.env");
      const output = generateTypeScriptTypes(parsed);
      expect(output).toContain("/** Main database connection URL */");
    });

    it("should not include a JSDoc comment when there is no description", () => {
      const parsed = parseEnvFileContent("DATABASE_URL=postgresql://localhost/db", "/test.env");
      const output = generateTypeScriptTypes(parsed);
      expect(output).not.toContain("/**");
    });

    it("should close the namespace block", () => {
      const parsed = parseEnvFileContent("KEY=value", "/test.env");
      const output = generateTypeScriptTypes(parsed);
      expect(output).toContain("  }");
      expect(output).toContain("}");
    });
  });

  describe("EnvVars type", () => {
    it("should export the EnvVars type", () => {
      const parsed = parseEnvFileContent("KEY=value", "/test.env");
      const output = generateTypeScriptTypes(parsed);
      expect(output).toContain("export type EnvVars = {");
    });

    it("should use the semantic number type in EnvVars", () => {
      const parsed = parseEnvFileContent("PORT=3000", "/test.env");
      const output = generateTypeScriptTypes(parsed);
      expect(output).toContain("PORT: number;");
    });

    it("should use the semantic boolean type in EnvVars", () => {
      const parsed = parseEnvFileContent("DEBUG=true", "/test.env");
      const output = generateTypeScriptTypes(parsed);
      expect(output).toContain("DEBUG: boolean;");
    });

    it("should use string for url in EnvVars", () => {
      const parsed = parseEnvFileContent("APP_URL=https://example.com", "/test.env");
      const output = generateTypeScriptTypes(parsed);
      expect(output).toContain("APP_URL: string;");
    });

    it("should mark optional vars with ?: type in EnvVars", () => {
      const parsed = parseEnvFileContent("AUTH_SECRET=", "/test.env");
      const output = generateTypeScriptTypes(parsed);
      expect(output).toContain("AUTH_SECRET?: string;");
    });

    it("should close the EnvVars type block", () => {
      const parsed = parseEnvFileContent("KEY=value", "/test.env");
      const output = generateTypeScriptTypes(parsed);
      expect(output).toContain("};");
    });
  });

  describe("ServerEnvVars / ClientEnvVars", () => {
    it("should emit ServerEnvVars and ClientEnvVars when NEXT_PUBLIC_ vars exist", () => {
      const content = [
        "DATABASE_URL=postgresql://localhost/db",
        "NEXT_PUBLIC_API_URL=https://api.example.com",
      ].join("\n");
      const parsed = parseEnvFileContent(content, "/test.env");
      const output = generateTypeScriptTypes(parsed);
      expect(output).toContain('export type ServerEnvVars = Omit<EnvVars, "NEXT_PUBLIC_API_URL">');
      expect(output).toContain('export type ClientEnvVars = Pick<EnvVars, "NEXT_PUBLIC_API_URL">');
    });

    it("should NOT emit ServerEnvVars / ClientEnvVars when no NEXT_PUBLIC_ vars exist", () => {
      const parsed = parseEnvFileContent("DATABASE_URL=postgresql://localhost/db", "/test.env");
      const output = generateTypeScriptTypes(parsed);
      expect(output).not.toContain("ServerEnvVars");
      expect(output).not.toContain("ClientEnvVars");
    });

    it("should include all NEXT_PUBLIC_ keys in the ClientEnvVars union", () => {
      const content = [
        "DATABASE_URL=postgresql://localhost/db",
        "NEXT_PUBLIC_API_URL=https://api.example.com",
        "NEXT_PUBLIC_APP_TITLE=My App",
      ].join("\n");
      const parsed = parseEnvFileContent(content, "/test.env");
      const output = generateTypeScriptTypes(parsed);
      expect(output).toContain('"NEXT_PUBLIC_API_URL"');
      expect(output).toContain('"NEXT_PUBLIC_APP_TITLE"');
    });
  });

  describe("annotatedType override", () => {
    it("should use annotatedType string over inferred number in EnvVars", () => {
      const content = ["# @type string", "PORT=3000"].join("\n");
      const parsed = parseEnvFileContent(content, "/test.env");
      const output = generateTypeScriptTypes(parsed);
      expect(output).toContain("PORT: string;");
      expect(output).not.toContain("PORT: number;");
    });

    it("should use annotatedType boolean even when value looks like a string", () => {
      const content = ["# @type boolean", "FEATURE_FLAG=enabled"].join("\n");
      const parsed = parseEnvFileContent(content, "/test.env");
      const output = generateTypeScriptTypes(parsed);
      expect(output).toContain("FEATURE_FLAG: boolean;");
    });

    it("should suppress number coercion hint in ProcessEnv when annotatedType is string", () => {
      const content = ["# @type string", "PORT=3000"].join("\n");
      const parsed = parseEnvFileContent(content, "/test.env");
      const output = generateTypeScriptTypes(parsed);
      // annotatedType=string means no number coercion hint
      expect(output).not.toContain("// coerce to number");
    });
  });
});

describe("generateEnvValidation", () => {
  describe("output structure", () => {
    it("should emit a validateEnv function export", () => {
      const parsed = parseEnvFileContent("KEY=value", "/test.env");
      const output = generateEnvValidation(parsed);
      expect(output).toContain("export function validateEnv()");
    });
  });

  describe("required variable validation", () => {
    it("should include required vars in the validation array", () => {
      const parsed = parseEnvFileContent("DATABASE_URL=postgresql://localhost/db", "/test.env");
      const output = generateEnvValidation(parsed);
      expect(output).toContain('"DATABASE_URL"');
    });

    it("should include multiple required vars", () => {
      const content = ["DATABASE_URL=postgresql://localhost/db", "API_KEY=abc123"].join("\n");
      const parsed = parseEnvFileContent(content, "/test.env");
      const output = generateEnvValidation(parsed);
      expect(output).toContain('"DATABASE_URL"');
      expect(output).toContain('"API_KEY"');
    });

    it("should throw on a missing required var", () => {
      const parsed = parseEnvFileContent("DATABASE_URL=postgresql://localhost/db", "/test.env");
      const output = generateEnvValidation(parsed);
      expect(output).toContain("throw new Error");
    });
  });

  describe("optional variable exclusion", () => {
    it("should NOT include optional vars in the validation array", () => {
      const parsed = parseEnvFileContent("AUTH_SECRET=", "/test.env");
      const output = generateEnvValidation(parsed);
      expect(output).not.toContain('"AUTH_SECRET"');
    });
  });

  describe("no required variables", () => {
    it("should emit a valid function body when no vars are required", () => {
      const content = ["OPT_VAR=", "ANOTHER="].join("\n");
      const parsed = parseEnvFileContent(content, "/test.env");
      const output = generateEnvValidation(parsed);
      expect(output).toContain("validateEnv");
      expect(output).not.toContain('"OPT_VAR"');
      expect(output).not.toContain('"ANOTHER"');
    });
  });

  describe("@required annotation override", () => {
    it("should include a @required empty var in the validation list", () => {
      const content = ["# @required", "CRITICAL_KEY="].join("\n");
      const parsed = parseEnvFileContent(content, "/test.env");
      const output = generateEnvValidation(parsed);
      expect(output).toContain('"CRITICAL_KEY"');
    });
  });
});
